name: combustile_editor
description: Editor for the combustile package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  code_text_field: ^1.1.0
  combustile:
    path: ../combustile
  equatable: ^2.0.5
  file_selector: ^0.9.2+4
  flame: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  highlight: ^0.7.0
  intl: ^0.18.0
  nes_ui:
    git:
      url: https://github.com/erickzanardo/nes_ui.git
  path: ^1.8.3
  project_repository:
    path: packages/project_repository

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
