name: combustile
description: A simple tile system, that provides a declarative API, with Flame Component System in mind
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flame: ^1.7.0
  flutter:
    sdk: flutter
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0


dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: feat/bump-ordered-set
      path: packages/flame
