name: combustile
description: A simple tile system, that provides a declarative API, with Flame Component System in mind
version: 0.1.0
repository: https://github.com/cherrybit-studios/combustile

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.7.3
  flutter:
    sdk: flutter
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
