name: Deploy

on: workflow_dispatch

env:
  ITCH_USERNAME: cherrybit
  ITCH_GAME_ID: combustile-editor

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - run: cd packages/combustile_editor && flutter build linux
      - name: Zips the build
        uses: papeloto/action-zip@v1
        with:
          files: ./packages/combustile_editor/build/linux/x64/release/bundle/
          dest: linux.zip
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: linux.zip

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - run: cd packages/combustile_editor && flutter build windows
      - name: Zips the build
        uses: papeloto/action-zip@v1
        with:
          files: ./packages/combustile_editor/build/windows/runner/Release/
          dest: windows.zip
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: windows.zip

  build_osx:
    name: Build OSX
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2

      - run: cd packages/combustile_editor && flutter build macos
      - name: Zips the build
        run: cd ./packages/combustile_editor/build/macos/Build/Products/Release && zip -r osx.zip Combustile\ Editor.app
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: osx
          path: ./packages/combustile_editor/build/macos/Build/Products/Release/osx.zip


  release_desktop:
    needs: [build_linux, build_osx, build_windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: linux

      - name: Download Mac artifact
        uses: actions/download-artifact@v2
        with:
          name: osx

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: windows

      - name: Publish Linux
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCH_KEY}}
          gameData: linux.zip
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: linux

      - name: Publish Windows
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCH_KEY}}
          gameData: windows.zip
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: windows

      - name: Publish OSX
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCH_KEY}}
          gameData: osx.zip
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: osx
